[package]
name = "uucore-macros"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { features=["extra-traits", "full"], version="1.0" } ## 'extra-traits' for Debug traits
