[package]
name = "uucore_procs"
version = "0.0.2"
authors = []
license = "MIT"
description = "uutils ~ 'uucore' proc-macros"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version="1.0" }

[features]
default = []
## non-default features
debug = ["syn/extra-traits"] ## add Debug traits to syn structs (for `println!("{:?}", ...)`)
